"""
Prompt templates for DealFlow AI Copilot agents.

This package contains all prompts used by the multi-agent system for:
- Extraction Agent: Data extraction from pitch decks
- Analysis Agent: Business model and market analysis
- Risk Agent: Risk identification and assessment
- Valuation Agent: Multiple valuation methodologies
"""

from prompts.analysis_prompts import (
    ANALYSIS_SYSTEM_PROMPT,
    BUSINESS_MODEL_ANALYSIS_PROMPT,
    COMPETITIVE_ANALYSIS_PROMPT,
    GROWTH_ANALYSIS_PROMPT,
    INVESTMENT_THESIS_PROMPT,
    MARKET_ANALYSIS_PROMPT,
    TEAM_ASSESSMENT_PROMPT,
)
from prompts.extraction_prompts import (
    EXTRACTION_MAIN_PROMPT,
    EXTRACTION_SYSTEM_PROMPT,
    FINANCIAL_VALIDATION_PROMPT,
    VISION_EXTRACTION_PROMPT,
)
from prompts.risk_prompts import (
    DATA_CONSISTENCY_PROMPT,
    FINANCIAL_RISK_PROMPT,
    MARKET_RISK_PROMPT,
    OPERATIONAL_RISK_PROMPT,
    RISK_SYNTHESIS_PROMPT,
    RISK_SYSTEM_PROMPT,
    TEAM_RISK_PROMPT,
)
from prompts.valuation_prompts import (
    COMPARABLE_ANALYSIS_PROMPT,
    DCF_VALUATION_PROMPT,
    REVENUE_MULTIPLE_PROMPT,
    SCENARIO_ANALYSIS_PROMPT,
    SENSITIVITY_ANALYSIS_PROMPT,
    VALUATION_SYNTHESIS_PROMPT,
    VALUATION_SYSTEM_PROMPT,
)

__all__ = [
    # Extraction
    "EXTRACTION_SYSTEM_PROMPT",
    "EXTRACTION_MAIN_PROMPT",
    "VISION_EXTRACTION_PROMPT",
    "FINANCIAL_VALIDATION_PROMPT",
    # Analysis
    "ANALYSIS_SYSTEM_PROMPT",
    "BUSINESS_MODEL_ANALYSIS_PROMPT",
    "MARKET_ANALYSIS_PROMPT",
    "COMPETITIVE_ANALYSIS_PROMPT",
    "GROWTH_ANALYSIS_PROMPT",
    "INVESTMENT_THESIS_PROMPT",
    "TEAM_ASSESSMENT_PROMPT",
    # Risk
    "RISK_SYSTEM_PROMPT",
    "FINANCIAL_RISK_PROMPT",
    "TEAM_RISK_PROMPT",
    "MARKET_RISK_PROMPT",
    "OPERATIONAL_RISK_PROMPT",
    "DATA_CONSISTENCY_PROMPT",
    "RISK_SYNTHESIS_PROMPT",
    # Valuation
    "VALUATION_SYSTEM_PROMPT",
    "REVENUE_MULTIPLE_PROMPT",
    "COMPARABLE_ANALYSIS_PROMPT",
    "DCF_VALUATION_PROMPT",
    "SCENARIO_ANALYSIS_PROMPT",
    "SENSITIVITY_ANALYSIS_PROMPT",
    "VALUATION_SYNTHESIS_PROMPT",
]
